# Baselines

In [23]:
import pandas as pd
import numpy as np

imputation = {'ARIMA':'ARIMA','INTERPOLATION':'Interpolation','FF':'Forward fill','NO_IMP':'Model-based'}
loss_type = {'bce':'BCE','mse':'MSE(logit)'}

In [30]:
base_results = pd.read_csv("test_outputs/baseline_output.txt",sep=" ", header=None)

datas = {}
for _,row in base_results.iterrows():
    model = row[0]
    mse = row[1]
    mae = row[2]
    mape = row[3]
    mape2 = row[4]
    r2 = row[5]
    imp_type = imputation[row[6]]
    loss = loss_type[row[8]]

    key = (model,imp_type,loss) 
    if key not in datas:
        datas[key] = [[],[],[],[],[]]
    datas[key][0].append(mse)
    datas[key][1].append(mae)
    datas[key][2].append(mape)
    datas[key][3].append(mape2)
    datas[key][4].append(r2)

pd_data = []
for model,imp_type,loss in datas:
    key = (model,imp_type,loss)
    pd_data.append([model,imp_type,loss, "%.2f" % (np.asarray(datas[key][0]).mean() / 1e17)+ "\u00B1" + "%.2f" % (np.asarray(datas[key][0]).std() / 1e17),"%.2f" % (np.asarray(datas[key][1]).mean() / 1e8) + "\u00B1" + "%.2f" % (np.asarray(datas[key][1]).std() / 1e8),"%.2f" % np.asarray(datas[key][2]).mean()+ "\u00B1"+"%.2f" % np.asarray(datas[key][2]).std(),"%.2f" % np.asarray(datas[key][3]).mean()+ "\u00B1"+ "%.2f" % np.asarray(datas[key][3]).std(),"%.2f" % np.asarray(datas[key][4]).mean()+ "\u00B1"+ "%.2f" % np.asarray(datas[key][4]).std()])

In [31]:
base_df = pd.DataFrame(pd_data,columns=['Model',"Imputation","Loss","MSE, x10^17","MAE, x10^8","MAPE_all","MAPE_large","R^2"])

,Model,Imputation,Loss,"MSE, x10^17","MAE, x10^8",MAPE_all,MAPE_large,R^2
0,TKAN,Forward fill,BCE,1.38±0.40,1.73±0.58,41.80±71.80,0.35±0.09,0.76±0.11
1,TKAN,Forward fill,MSE(logit),3.41±3.02,2.14±1.10,6.47±9.36,0.43±0.23,0.58±0.36
2,LSTM,Forward fill,BCE,1.76±0.18,1.57±0.06,10.28±3.54,0.36±0.02,0.73±0.07
3,LSTM,Forward fill,MSE(logit),1.97±0.24,1.76±0.17,2.56±0.14,0.40±0.03,0.74±0.03
4,GRU,Forward fill,BCE,1.57±0.57,1.53±0.18,13.88±7.52,0.33±0.02,0.77±0.04
5,GRU,Forward fill,MSE(logit),2.33±0.71,1.85±0.24,2.64±0.72,0.46±0.02,0.65±0.04
6,TKAN,Interpolation,BCE,1.61±0.47,1.60±0.16,7.06±2.53,0.33±0.02,0.78±0.05
7,TKAN,Interpolation,MSE(logit),1.85±0.53,1.53±0.19,2.28±0.66,0.31±0.02,0.74±0.05
8,LSTM,Interpolation,BCE,1.37±0.34,1.52±0.15,5.97±3.47,0.32±0.02,0.80±0.03
9,LSTM,Interpolation,MSE(logit),2.31±0.55,1.87±0.19,3.02±1.31,0.43±0.06,0.67±0.09
10,GRU,Interpolation,BCE,1.53±0.45,1.53±0.15,11.34±5.31,0.33±0.03,0.78±0.05
11,GRU,Interpolation,MSE(logit),2.54±1.03,1.93±0.32,3.19±1.71,0.48±0.08,0.65±0.11
12,TKAN,Model-based,BCE,1.71±0.29,1.60±0.13,7.91±2.32,0.33±0.01,0.77±0.04
13,TKAN,Model-based,MSE(logit),3.23±2.09,2.12±0.93,10.59±16.22,0.44±0.21,0.52±0.33
14,LSTM,Model-based,BCE,1.23±0.39,1.54±0.20,13.67±6.05,0.34±0.03,0.80±0.03
15,LSTM,Model-based,MSE(logit),2.48±0.42,2.01±0.16,2.29±0.92,0.51±0.03,0.64±0.04
16,GRU,Model-based,BCE,1.94±0.22,1.79±0.12,13.39±3.22,0.35±0.02,0.76±0.02
17,GRU,Model-based,MSE(logit),2.14±0.48,1.80±0.21,3.27±0.93,0.46±0.10,0.70±0.06
18,TKAN,ARIMA,BCE,1.47±0.35,1.52±0.13,5.55±2.71,0.32±0.02,0.79±0.03
19,TKAN,ARIMA,MSE(logit),2.32±1.88,1.70±0.76,3.58±5.64,0.35±0.12,0.68±0.21
20,LSTM,ARIMA,BCE,1.39±0.38,1.49±0.13,7.61±4.22,0.33±0.03,0.79±0.06
21,LSTM,ARIMA,MSE(logit),2.67±0.64,1.99±0.24,2.66±1.08,0.47±0.05,0.63±0.06
22,GRU,ARIMA,BCE,1.53±0.41,1.58±0.18,10.17±3.56,0.34±0.03,0.77±0.05
23,GRU,ARIMA,MSE(logit),2.50±0.57,1.89±0.20,2.63±0.98,0.46±0.05,0.65±0.06

# Transformers

In [34]:
tr_results = pd.read_csv("test_outputs/log.txt",sep=" ", header=None)

In [35]:
tr_results

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14
0,Transformer:,encoder,True,1.609739e+17,1.351752e+08,0.877362,0.282776,0.779087,1,1,True,FF,True,mse,NaN
1,Transformer:,encoder,True,2.269367e+17,1.793940e+08,1.260066,0.491108,0.592676,1,1,True,FF,True,mse,NaN
2,Transformer:,encoder,True,1.404650e+17,1.562661e+08,0.957177,0.365939,0.803750,1,1,True,FF,True,mse,NaN
3,Transformer:,encoder,True,1.582851e+17,1.377629e+08,1.026422,0.272878,0.734358,1,1,True,FF,True,mse,NaN
4,Transformer:,encoder,True,1.140895e+17,1.311438e+08,1.004509,0.305886,0.812156,1,1,True,FF,True,mse,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1090,Transformer:,encoder,False,2.476669e+17,2.190510e+08,3.030865,0.335126,0.733142,3,2,True,ARIMA,True,bce,NaN
1091,Transformer:,encoder,False,6.042476e+16,1.082959e+08,5.098692,0.267003,0.897214,3,2,True,ARIMA,True,bce,NaN
1092,Transformer:,encoder,False,1.603391e+17,1.599741e+08,26.375350,0.316303,0.785093,3,2,True,ARIMA,True,bce,NaN
1093,Transformer:,encoder,False,8.226730e+16,1.205377e+08,5.915015,0.320475,0.849582,3,2,True,ARIMA,True,bce,NaN
1094,Transformer:,encoder,False,1.295237e+17,1.140454e+08,1.468870,0.303879,0.816617,3,2,False,ARIMA,True,mse,NaN

In [46]:

datas = {}
for _,row in tr_results.iterrows():
    model = row[0]+row[1]
    mse = row[3]
    mae = row[4]
    mape = row[5]
    mape2 = row[6]
    r2 = row[7]
    imp_type = imputation[row[11]]
    loss = loss_type[row[13]]
    L = row[8]
    heads = row[9]
    if row[2]:
        fft = "+"
    else:
        fft = "-"

    if row[10]:
        recurrent = "+"
    else:
        recurrent = "-"
    
    key = (model,imp_type,loss,L,heads,fft,recurrent) 
    if key not in datas:
        datas[key] = [[],[],[],[],[]]
    datas[key][0].append(mse)
    datas[key][1].append(mae)
    datas[key][2].append(mape)
    datas[key][3].append(mape2)
    datas[key][4].append(r2)

pd_data = []
for model,imp_type,loss,L,heads,fft,recurrent in datas:
    key = (model,imp_type,loss,L,heads,fft,recurrent)
    pd_data.append([model,imp_type,loss,L,heads,fft,recurrent, "%.2f" % (np.asarray(datas[key][0]).mean() / 1e17)+ "\u00B1" + "%.2f" % (np.asarray(datas[key][0]).std() / 1e17),"%.2f" % (np.asarray(datas[key][1]).mean() / 1e8) + "\u00B1" + "%.2f" % (np.asarray(datas[key][1]).std() / 1e8),"%.2f" % np.asarray(datas[key][2]).mean()+ "\u00B1"+"%.2f" % np.asarray(datas[key][2]).std(),"%.2f" % np.asarray(datas[key][3]).mean()+ "\u00B1"+ "%.2f" % np.asarray(datas[key][3]).std(),"%.2f" % np.asarray(datas[key][4]).mean()+ "\u00B1"+ "%.2f" % np.asarray(datas[key][4]).std()])

In [47]:
enc_res = pd.DataFrame(pd_data,columns=['Model',"Imputation","Loss","Layers","Attn. heads","FFT","Recurrent embeddings","MSE, x10^17","MAE, x10^8","MAPE_all","MAPE_large","R^2"])

In [48]:
pd.set_option('display.max_rows', 500)

enc_res

,Model,Imputation,Loss,Layers,Attn. heads,FFT,Recurrent embeddings,"MSE, x10^17","MAE, x10^8",MAPE_all,MAPE_large,R^2
0,Transformer:encoder,Forward fill,MSE(logit),1,1,+,+,1.60±0.37,1.48±0.18,1.03±0.13,0.34±0.08,0.74±0.08
1,Transformer:encoder,Forward fill,BCE,1,1,+,+,1.03±0.46,1.28±0.22,12.94±5.73,0.30±0.05,0.84±0.06
2,Transformer:encoder,Forward fill,MSE(logit),1,1,+,-,6.68±1.46,3.61±0.40,3.40±1.22,0.69±0.08,0.15±0.13
3,Transformer:encoder,Forward fill,BCE,1,1,+,-,6.01±2.07,4.41±0.42,93.55±97.00,0.59±0.07,0.20±0.15
4,Transformer:encoder,Forward fill,MSE(logit),1,2,+,+,2.18±0.62,1.73±0.24,1.04±0.18,0.38±0.05,0.69±0.08
5,Transformer:encoder,Forward fill,BCE,1,2,+,+,1.01±0.40,1.32±0.15,13.37±12.45,0.28±0.02,0.86±0.04
6,Transformer:encoder,Forward fill,MSE(logit),1,2,+,-,6.22±1.83,3.50±0.55,3.92±1.41,0.70±0.07,0.25±0.13
7,Transformer:encoder,Forward fill,BCE,1,2,+,-,7.66±1.28,5.22±0.13,158.10±65.71,0.52±0.05,-0.02±0.02
8,Transformer:encoder,Forward fill,MSE(logit),1,4,+,+,2.63±1.00,1.70±0.50,1.21±0.26,0.44±0.05,0.57±0.10
9,Transformer:encoder,Forward fill,BCE,1,4,+,+,0.79±0.39,1.13±0.26,6.32±3.95,0.25±0.05,0.88±0.05
10,Transformer:encoder,Forward fill,MSE(logit),1,4,+,-,5.97±1.61,3.31±0.49,5.69±2.05,0.71±0.09,0.15±0.16
11,Transformer:encoder,Forward fill,BCE,1,4,+,-,5.33±1.59,4.18±0.48,82.81±75.30,0.57±0.07,0.26±0.14
12,Transformer:encoder,Forward fill,MSE(logit),2,1,+,+,2.71±1.11,1.69±0.41,1.11±0.18,0.37±0.03,0.59±0.12
13,Transformer:encoder,Forward fill,BCE,2,1,+,+,1.25±0.45,1.33±0.32,8.34±6.38,0.30±0.03,0.82±0.02
14,Transformer:encoder,Forward fill,MSE(logit),2,1,+,-,5.43±1.59,3.20±0.38,4.32±1.71,0.67±0.04,0.31±0.15
15,Transformer:encoder,Forward fill,BCE,2,1,+,-,6.53±1.98,4.12±0.54,84.29±110.03,0.59±0.07,0.24±0.14
16,Transformer:encoder,Forward fill,MSE(logit),2,2,+,+,2.11±1.13,1.69±0.57,1.17±0.32,0.37±0.08,0.69±0.21
17,Transformer:encoder,Forward fill,BCE,2,2,+,+,1.83±0.57,1.69±0.23,8.14±2.85,0.32±0.04,0.76±0.06
18,Transformer:encoder,Forward fill,MSE(logit),2,2,+,-,6.84±3.34,3.54±0.80,4.81±2.68,0.68±0.07,0.20±0.14
19,Transformer:encoder,Forward fill,BCE,2,2,+,-,5.17±1.32,3.59±0.68,102.70±88.77,0.60±0.02,0.25±0.19
20,Transformer:encoder,Forward fill,MSE(logit),2,4,+,+,1.54±0.86,1.43±0.26,0.87±0.06,0.32±0.03,0.79±0.12
21,Transformer:encoder,Forward fill,BCE,2,4,+,+,0.84±0.32,1.15±0.21,6.48±2.33,0.27±0.05,0.86±0.04
22,Transformer:encoder,Forward fill,MSE(logit),2,4,+,-,4.70±1.50,2.81±0.53,4.81±1.39,0.67±0.05,0.23±0.12
23,Transformer:encoder,Forward fill,BCE,2,4,+,-,6.13±1.59,3.81±0.56,47.83±25.29,0.63±0.05,0.11±0.07
24,Transformer:encoder,Forward fill,MSE(logit),3,1,+,+,2.30±0.79,1.68±0.31,1.07±0.08,0.34±0.04,0.70±0.05
25,Transformer:encoder,Forward fill,BCE,3,1,+,+,1.90±0.64,1.62±0.29,5.52±3.09,0.32±0.02,0.78±0.04
26,Transformer:encoder,Forward fill,MSE(logit),3,1,+,-,5.10±0.47,3.09±0.34,4.33±1.30,0.67±0.11,0.35±0.02
27,Transformer:encoder,Forward fill,BCE,3,1,+,-,5.15±1.20,3.57±0.51,29.56±9.89,0.61±0.07,0.26±0.12
28,Transformer:encoder,Forward fill,MSE(logit),3,2,+,+,2.82±0.47,1.75±0.26,1.14±0.31,0.38±0.05,0.57±0.05
29,Transformer:encoder,Forward fill,BCE,3,2,+,+,0.95±0.36,1.13±0.20,6.73±2.38,0.28±0.05,0.85±0.06
30,Transformer:encoder,Forward fill,MSE(logit),3,2,+,-,4.35±0.63,2.98±0.32,3.24±0.71,0.66±0.08,0.40±0.05
31,Transformer:encoder,Forward fill,BCE,3,2,+,-,4.45±0.76,3.24±0.19,28.82±6.16,0.60±0.06,0.29±0.10
32,Transformer:encoder,Forward fill,MSE(logit),3,4,+,+,1.61±0.99,1.48±0.35,0.98±0.15,0.31±0.07,0.78±0.14
33,Transformer:encoder,Forward fill,BCE,3,4,+,+,1.55±0.68,1.41±0.36,12.02±8.30,0.36±0.12,0.77±0.09
34,Transformer:encoder,Forward fill,MSE(logit),3,4,+,-,4.93±1.37,3.19±0.55,3.91±1.08,0.67±0.09,0.31±0.09
35,Transformer:encoder,Forward fill,BCE,3,4,+,-,6.69±0.78,4.12±0.28,40.27±22.37,0.60±0.06,0.11±0.12
36,Transformer:encoder,Forward fill,MSE(logit),4,1,+,+,1.36±0.42,1.35±0.23,0.90±0.05,0.33±0.02,0.77±0.06
37,Transformer:encoder,Forward fill,BCE,4,1,+,+,1.15±0.46,1.38±0.29,5.12±2.22,0.29±0.03,0.85±0.04
38,Transformer:encoder,Forward fill,MSE(logit),4,1,+,-,5.16±1.71,3.24±0.55,10.54±11.46,0.62±0.04,0.24±0.06
39,Transformer:encoder,Forward fill,BCE,4,1,+,-,3.78±1.04,3.06±0.46,27.06±10.96,0.57±0.05,0.37±0.04
40,Transformer:encoder,Forward fill,MSE(logit),4,2,+,+,2.82±0.97,1.68±0.23,1.17±0.10,0.35±0.05,0.62±0.09
41,Transformer:encoder,Forward fill,BCE,4,2,+,+,1.03±0.21,1.33±0.14,7.41±1.35,0.30±0.02,0.84±0.03
42,Transformer:encoder,Forward fill,MSE(logit),4,2,+,-,5.10±1.73,2.94±0.47,9.61±6.62,0.66±0.06,0.28±0.18
43,Transformer:encoder,Forward fill,BCE,4,2,+,-,5.52±1.25,3.71±0.45,46.39±31.38,0.62±0.07,0.20±0.12
44,Transformer:encoder,Forward fill,MSE(logit),4,4,+,+,112.40±3.00,32.89±0.56,467.51±67.11,3.38±0.12,-17.69±4.11
45,Transformer:encoder,Forward fill,BCE,4,4,+,+,1.96±1.54,1.95±1.06,19.35±32.26,0.32±0.12,0.71±0.29
46,Transformer:encoder,Forward fill,MSE(logit),4,4,+,-,4.95±1.32,3.01±0.44,4.65±1.97,0.66±0.05,0.34±0.06
47,Transformer:encoder,Forward fill,BCE,4,4,+,-,5.52±1.43,3.69±0.44,37.92±33.77,0.65±0.10,0.25±0.15
48,Transformer:encoder,Interpolation,MSE(logit),1,1,+,+,1.71±0.64,1.51±0.24,0.96±0.13,0.33±0.01,0.75±0.11
49,Transformer:encoder,Interpolation,BCE,1,1,+,+,1.27±0.41,1.46±0.30,13.12±11.63,0.30±0.03,0.84±0.03
50,Transformer:encoder,Interpolation,MSE(logit),1,1,+,-,5.42±1.41,3.09±0.53,3.56±0.47,0.65±0.09,0.26±0.15
51,Transformer:encoder,Interpolation,BCE,1,1,+,-,6.69±2.37,4.42±0.82,55.59±29.87,0.53±0.04,0.18±0.16
52,Transformer:encoder,Interpolation,MSE(logit),1,2,+,+,3.91±1.35,2.17±0.45,1.23±0.21,0.38±0.05,0.52±0.15
53,Transformer:encoder,Interpolation,BCE,1,2,+,+,1.07±0.40,1.34±0.23,9.12±7.63,0.29±0.05,0.85±0.05
54,Transformer:encoder,Interpolation,MSE(logit),1,2,+,-,4.91±1.22,3.08±0.40,4.63±2.56,0.68±0.12,0.19±0.11
55,Transformer:encoder,Interpolation,BCE,1,2,+,-,5.82±1.61,4.50±0.40,73.48±19.07,0.52±0.04,0.12±0.06
56,Transformer:encoder,Interpolation,MSE(logit),1,4,+,+,2.46±0.48,1.68±0.16,1.11±0.06,0.38±0.04,0.63±0.04
57,Transformer:encoder,Interpolation,BCE,1,4,+,+,1.12±0.39,1.21±0.22,10.15±4.52,0.32±0.04,0.81±0.04
58,Transformer:encoder,Interpolation,MSE(logit),1,4,+,-,5.97±0.90,3.14±0.22,2.89±1.02,0.66±0.08,0.21±0.13
59,Transformer:encoder,Interpolation,BCE,1,4,+,-,7.18±1.20,5.10±0.28,157.29±71.37,0.51±0.01,-0.00±0.00
60,Transformer:encoder,Interpolation,MSE(logit),2,1,+,+,3.66±1.14,2.11±0.40,1.07±0.11,0.39±0.05,0.58±0.08
61,Transformer:encoder,Interpolation,BCE,2,1,+,+,1.21±0.42,1.33±0.29,7.55±4.62,0.29±0.03,0.82±0.05
62,Transformer:encoder,Interpolation,MSE(logit),2,1,+,-,4.38±1.04,2.89±0.45,3.34±0.71,0.62±0.03,0.35±0.07
63,Transformer:encoder,Interpolation,BCE,2,1,+,-,4.22±0.87,3.25±0.59,24.27±7.63,0.61±0.08,0.31±0.13
64,Transformer:encoder,Interpolation,MSE(logit),2,2,+,+,2.22±1.08,1.59±0.23,1.11±0.11,0.34±0.03,0.68±0.16
65,Transformer:encoder,Interpolation,BCE,2,2,+,+,1.20±0.46,1.30±0.25,3.81±1.56,0.30±0.05,0.83±0.04
66,Transformer:encoder,Interpolation,MSE(logit),2,2,+,-,4.32±1.44,2.90±0.49,3.14±0.73,0.60±0.08,0.36±0.09
67,Transformer:encoder,Interpolation,BCE,2,2,+,-,4.37±1.40,3.44±0.47,31.59±17.69,0.57±0.03,0.35±0.10
68,Transformer:encoder,Interpolation,MSE(logit),2,4,+,+,2.16±0.90,1.56±0.23,1.23±0.13,0.37±0.02,0.68±0.13
69,Transformer:encoder,Interpolation,BCE,2,4,+,+,1.43±0.28,1.41±0.06,5.24±1.38,0.32±0.02,0.81±0.03
70,Transformer:encoder,Interpolation,MSE(logit),2,4,+,-,6.45±1.49,3.46±0.49,6.82±2.65,0.81±0.12,0.03±0.23
71,Transformer:encoder,Interpolation,BCE,2,4,+,-,4.20±1.03,2.97±0.46,25.45±6.85,0.73±0.09,0.32±0.07
72,Transformer:encoder,Interpolation,MSE(logit),3,1,+,+,1.76±0.89,1.53±0.38,1.21±0.34,0.36±0.08,0.76±0.07
73,Transformer:encoder,Interpolation,BCE,3,1,+,+,0.91±0.34,1.20±0.16,3.97±2.88,0.28±0.03,0.86±0.05
74,Transformer:encoder,Interpolation,MSE(logit),3,1,+,-,5.19±0.95,3.03±0.28,4.63±1.72,0.68±0.07,0.23±0.14
75,Transformer:encoder,Interpolation,BCE,3,1,+,-,4.80±0.54,3.55±0.23,50.16±47.81,0.66±0.05,0.25±0.11
76,Transformer:encoder,Interpolation,MSE(logit),3,2,+,+,3.48±1.64,2.02±0.48,1.21±0.08,0.39±0.07,0.51±0.20
77,Transformer:encoder,Interpolation,BCE,3,2,+,+,0.94±0.25,1.23±0.14,7.29±2.85,0.25±0.01,0.87±0.02
78,Transformer:encoder,Interpolation,MSE(logit),3,2,+,-,4.56±1.10,2.92±0.51,4.54±2.57,0.65±0.07,0.33±0.13
79,Transformer:encoder,Interpolation,BCE,3,2,+,-,5.80±1.20,4.05±0.45,35.55±22.95,0.60±0.05,0.25±0.12
80,Transformer:encoder,Interpolation,MSE(logit),3,4,+,+,2.33±0.79,1.68±0.32,1.07±0.18,0.32±0.03,0.70±0.04
81,Transformer:encoder,Interpolation,BCE,3,4,+,+,0.91±0.36,1.17±0.23,4.46±1.36,0.27±0.03,0.87±0.03
82,Transformer:encoder,Interpolation,MSE(logit),3,4,+,-,4.59±1.38,2.98±0.54,4.19±1.45,0.65±0.09,0.30±0.08
83,Transformer:encoder,Interpolation,BCE,3,4,+,-,5.80±1.71,3.74±0.82,55.00±22.26,0.59±0.07,0.19±0.15
84,Transformer:encoder,Interpolation,MSE(logit),4,1,+,+,8.08±2.56,3.98±0.95,9.69±2.58,0.89±0.01,-0.17±0.06
85,Transformer:encoder,Interpolation,BCE,4,1,+,+,0.91±0.46,1.20±0.24,4.20±1.19,0.26±0.04,0.87±0.05
86,Transformer:encoder,Interpolation,MSE(logit),4,1,+,-,7.08±2.78,3.75±0.90,6.25±2.09,0.81±0.15,0.02±0.28
87,Transformer:encoder,Interpolation,BCE,4,1,+,-,5.93±2.15,3.58±0.78,37.12±21.17,0.66±0.05,0.25±0.13
88,Transformer:encoder,Interpolation,MSE(logit),4,2,+,+,2.89±0.89,1.83±0.24,0.97±0.07,0.36±0.04,0.63±0.11
89,Transformer:encoder,Interpolation,BCE,4,2,+,+,1.03±0.45,1.26±0.25,6.66±2.96,0.31±0.05,0.85±0.03
90,Transformer:encoder,Interpolation,MSE(logit),4,2,+,-,5.65±1.66,3.22±0.60,5.64±2.72,0.67±0.08,0.27±0.07
91,Transformer:encoder,Interpolation,BCE,4,2,+,-,6.04±1.73,3.79±0.52,26.44±12.15,0.67±0.09,0.14±0.14
92,Transformer:encoder,Interpolation,MSE(logit),4,4,+,+,19.49±28.13,7.68±9.84,81.31±138.85,0.92±0.99,-1.63±3.83
93,Transformer:encoder,Model-based,MSE(logit),1,1,+,+,2.31±0.49,1.73±0.32,1.03±0.18,0.40±0.10,0.68±0.04
94,Transformer:encoder,Model-based,BCE,1,1,+,+,1.63±0.89,1.59±0.43,3.78±1.43,0.31±0.05,0.81±0.08
95,Transformer:encoder,Model-based,MSE(logit),1,1,+,-,4.52±1.69,2.87±0.64,7.49±5.39,0.74±0.06,0.20±0.15
96,Transformer:encoder,Model-based,BCE,1,1,+,-,6.42±0.68,4.50±0.47,112.95±81.72,0.53±0.04,0.08±0.18
97,Transformer:encoder,Model-based,MSE(logit),1,2,+,+,2.48±0.89,1.60±0.25,1.25±0.33,0.37±0.03,0.65±0.11
98,Transformer:encoder,Model-based,BCE,1,2,+,+,3.96±2.98,3.10±1.80,81.01±76.31,0.37±0.10,0.48±0.39
99,Transformer:encoder,Model-based,MSE(logit),1,2,+,-,6.04±1.76,3.44±0.52,3.92±0.83,0.68±0.05,0.22±0.08
100,Transformer:encoder,Model-based,BCE,1,2,+,-,5.83±0.60,4.47±0.31,135.05±31.64,0.55±0.04,0.15±0.05
101,Transformer:encoder,Model-based,MSE(logit),1,4,+,+,1.58±0.58,1.43±0.28,1.01±0.20,0.38±0.10,0.78±0.08
102,Transformer:encoder,Model-based,BCE,1,4,+,+,1.99±1.50,1.72±0.87,14.34±10.81,0.33±0.04,0.73±0.18
103,Transformer:encoder,Model-based,MSE(logit),1,4,+,-,6.78±1.93,3.44±0.78,7.69±4.01,0.74±0.04,0.10±0.10
104,Transformer:encoder,Model-based,BCE,1,4,+,-,10.17±8.31,5.30±2.37,102.72±130.70,0.65±0.08,-0.36±1.05
105,Transformer:encoder,Model-based,MSE(logit),2,1,+,+,2.90±0.27,1.86±0.21,0.94±0.07,0.37±0.02,0.63±0.02
106,Transformer:encoder,Model-based,BCE,2,1,+,+,1.61±0.68,1.50±0.17,11.31±7.10,0.30±0.04,0.81±0.09
107,Transformer:encoder,Model-based,MSE(logit),2,1,+,-,6.68±1.43,3.51±0.57,3.79±1.21,0.76±0.11,0.14±0.23
108,Transformer:encoder,Model-based,BCE,2,1,+,-,4.15±0.52,3.67±0.26,121.03±38.99,0.56±0.03,0.27±0.07
109,Transformer:encoder,Model-based,MSE(logit),2,2,+,+,2.12±1.24,1.64±0.53,0.96±0.08,0.35±0.06,0.69±0.17
110,Transformer:encoder,Model-based,BCE,2,2,+,+,1.27±0.53,1.45±0.36,5.05±3.46,0.32±0.07,0.84±0.04
111,Transformer:encoder,Model-based,MSE(logit),2,2,+,-,5.86±1.01,3.47±0.22,4.79±2.55,0.75±0.04,0.14±0.09
112,Transformer:encoder,Model-based,BCE,2,2,+,-,6.55±1.28,4.39±0.66,73.56±77.17,0.61±0.06,0.08±0.07
113,Transformer:encoder,Model-based,MSE(logit),2,4,+,+,3.57±2.66,2.17±0.73,3.91±5.18,0.47±0.21,0.56±0.33
114,Transformer:encoder,Model-based,BCE,2,4,+,+,1.29±0.49,1.44±0.30,5.68±3.96,0.31±0.04,0.83±0.04
115,Transformer:encoder,Model-based,MSE(logit),2,4,+,-,3.99±0.68,2.77±0.43,3.77±1.89,0.67±0.09,0.33±0.13
116,Transformer:encoder,Model-based,BCE,2,4,+,-,4.70±1.15,3.48±0.26,29.98±9.99,0.60±0.06,0.30±0.12
117,Transformer:encoder,Model-based,MSE(logit),3,1,+,+,2.49±1.39,1.70±0.57,1.09±0.16,0.36±0.05,0.63±0.11
118,Transformer:encoder,Model-based,BCE,3,1,+,+,0.81±0.30,1.20±0.17,4.66±2.20,0.27±0.02,0.87±0.03
119,Transformer:encoder,Model-based,MSE(logit),3,1,+,-,5.46±0.85,2.89±0.35,4.04±1.48,0.70±0.04,0.29±0.06
120,Transformer:encoder,Model-based,BCE,3,1,+,-,5.23±1.25,3.47±0.62,19.87±2.74,0.66±0.08,0.27±0.13
121,Transformer:encoder,Model-based,MSE(logit),3,2,+,+,1.69±0.30,1.58±0.16,1.16±0.14,0.37±0.04,0.73±0.05
122,Transformer:encoder,Model-based,BCE,3,2,+,+,1.42±0.56,1.40±0.21,12.40±4.94,0.32±0.04,0.78±0.07
123,Transformer:encoder,Model-based,MSE(logit),3,2,+,-,6.67±1.20,3.69±0.53,10.97±8.26,0.80±0.13,-0.13±0.44
124,Transformer:encoder,Model-based,BCE,3,2,+,-,9.48±9.17,4.23±1.89,72.63±106.58,0.78±0.18,-0.61±1.83
125,Transformer:encoder,Model-based,MSE(logit),3,4,+,+,2.43±0.69,1.77±0.32,1.22±0.22,0.38±0.04,0.67±0.08
126,Transformer:encoder,Model-based,BCE,3,4,+,+,2.59±1.92,2.18±1.44,17.61±6.42,0.37±0.12,0.64±0.26
127,Transformer:encoder,Model-based,MSE(logit),3,4,+,-,5.53±1.56,3.51±0.46,7.47±5.62,0.71±0.07,0.20±0.12
128,Transformer:encoder,Model-based,BCE,3,4,+,-,5.03±1.33,3.68±0.59,40.47±11.99,0.61±0.06,0.19±0.14
129,Transformer:encoder,Model-based,MSE(logit),4,1,+,+,46.73±55.32,14.17±15.61,208.27±254.44,1.60±1.56,-5.31±7.45
130,Transformer:encoder,Model-based,BCE,4,1,+,+,1.42±0.63,1.41±0.35,4.71±1.91,0.31±0.06,0.81±0.08
131,Transformer:encoder,Model-based,MSE(logit),4,1,+,-,4.11±1.29,3.00±0.46,3.45±0.91,0.65±0.07,0.35±0.15
132,Transformer:encoder,Model-based,BCE,4,1,+,-,6.56±1.93,4.26±0.75,263.20±446.90,0.67±0.07,-0.05±0.19
133,Transformer:encoder,Model-based,MSE(logit),4,2,+,+,3.05±1.33,2.09±0.62,1.19±0.14,0.41±0.04,0.57±0.18
134,Transformer:encoder,Model-based,BCE,4,2,+,+,1.10±0.57,1.26±0.32,7.37±5.68,0.29±0.07,0.84±0.05
135,Transformer:encoder,Model-based,MSE(logit),4,2,+,-,4.74±0.80,2.88±0.46,5.14±2.53,0.69±0.09,0.22±0.15
136,Transformer:encoder,Model-based,BCE,4,2,+,-,5.12±0.97,3.57±0.42,51.89±32.71,0.66±0.11,0.25±0.08
137,Transformer:encoder,Model-based,MSE(logit),4,4,+,+,2.13±0.64,1.71±0.41,1.04±0.22,0.36±0.03,0.69±0.05
138,Transformer:encoder,Model-based,BCE,4,4,+,+,1.74±1.22,1.71±0.78,10.18±12.19,0.34±0.15,0.78±0.16
139,Transformer:encoder,Model-based,MSE(logit),4,4,+,-,6.02±2.33,3.43±1.06,6.31±3.82,0.71±0.04,0.22±0.12
140,Transformer:encoder,Model-based,BCE,4,4,+,-,5.37±0.43,3.70±0.31,38.21±32.85,0.68±0.05,0.30±0.05
141,Transformer:encoder,ARIMA,MSE(logit),1,1,+,+,2.82±0.68,1.72±0.21,1.11±0.32,0.38±0.03,0.61±0.08
142,Transformer:encoder,ARIMA,BCE,1,1,+,+,1.43±0.46,1.66±0.36,4.93±5.15,0.30±0.03,0.84±0.03
143,Transformer:encoder,ARIMA,MSE(logit),1,1,+,-,7.46±1.70,3.92±0.64,7.10±2.79,0.79±0.06,0.09±0.19
144,Transformer:encoder,ARIMA,BCE,1,1,+,-,6.87±1.96,4.31±0.75,37.82±12.43,0.58±0.03,0.19±0.13
145,Transformer:encoder,ARIMA,MSE(logit),1,2,+,+,1.83±0.35,1.67±0.24,1.07±0.10,0.33±0.02,0.74±0.04
146,Transformer:encoder,ARIMA,BCE,1,2,+,+,1.13±0.51,1.25±0.22,5.81±2.84,0.28±0.04,0.85±0.04
147,Transformer:encoder,ARIMA,MSE(logit),1,2,+,-,4.29±0.73,2.77±0.70,4.50±1.30,0.65±0.07,0.27±0.08
148,Transformer:encoder,ARIMA,BCE,1,2,+,-,4.48±0.68,3.65±0.37,61.71±18.07,0.58±0.10,0.30±0.13
149,Transformer:encoder,ARIMA,MSE(logit),1,4,+,+,2.13±0.64,1.55±0.27,1.19±0.17,0.34±0.03,0.68±0.02
150,Transformer:encoder,ARIMA,BCE,1,4,+,+,1.36±0.53,1.45±0.30,5.02±3.51,0.28±0.03,0.83±0.06
151,Transformer:encoder,ARIMA,MSE(logit),1,4,+,-,5.11±2.06,3.03±0.78,4.60±2.12,0.72±0.08,0.18±0.13
152,Transformer:encoder,ARIMA,BCE,1,4,+,-,5.18±0.37,4.06±0.52,103.04±71.29,0.59±0.10,0.23±0.12
153,Transformer:encoder,ARIMA,MSE(logit),2,1,+,+,2.26±0.55,1.64±0.22,1.18±0.27,0.36±0.05,0.66±0.06
154,Transformer:encoder,ARIMA,BCE,2,1,+,+,1.31±0.35,1.54±0.33,4.90±2.21,0.31±0.05,0.84±0.02
155,Transformer:encoder,ARIMA,MSE(logit),2,1,+,-,4.80±0.65,3.08±0.29,2.98±0.56,0.71±0.10,0.29±0.11
156,Transformer:encoder,ARIMA,BCE,2,1,+,-,4.37±0.61,3.33±0.23,20.57±12.20,0.62±0.02,0.34±0.08
157,Transformer:encoder,ARIMA,MSE(logit),2,2,+,+,1.60±0.70,1.37±0.30,1.09±0.21,0.31±0.05,0.74±0.08
158,Transformer:encoder,ARIMA,BCE,2,2,+,+,1.18±0.31,1.35±0.28,3.71±1.08,0.28±0.03,0.83±0.05
159,Transformer:encoder,ARIMA,MSE(logit),2,2,+,-,5.69±0.84,3.28±0.20,4.15±2.24,0.65±0.04,0.22±0.09
160,Transformer:encoder,ARIMA,BCE,2,2,+,-,5.58±3.10,3.85±0.96,33.48±13.82,0.59±0.04,0.32±0.13
161,Transformer:encoder,ARIMA,MSE(logit),2,4,+,+,2.22±0.65,1.75±0.39,0.89±0.13,0.36±0.07,0.71±0.07
162,Transformer:encoder,ARIMA,BCE,2,4,+,+,1.14±0.47,1.33±0.27,7.47±4.63,0.29±0.05,0.82±0.07
163,Transformer:encoder,ARIMA,MSE(logit),2,4,+,-,5.63±1.24,3.26±0.62,4.74±1.95,0.66±0.07,0.23±0.15
164,Transformer:encoder,ARIMA,BCE,2,4,+,-,6.03±0.21,4.97±0.12,165.61±19.61,0.52±0.02,-0.00±0.00
165,Transformer:encoder,ARIMA,MSE(logit),3,1,+,+,1.88±1.10,1.53±0.40,0.91±0.07,0.32±0.04,0.75±0.10
166,Transformer:encoder,ARIMA,BCE,3,1,+,+,1.10±0.28,1.29±0.12,2.83±1.15,0.28±0.02,0.85±0.02
167,Transformer:encoder,ARIMA,MSE(logit),3,1,+,-,5.09±1.56,3.19±0.57,6.22±2.54,0.74±0.07,0.27±0.04
168,Transformer:encoder,ARIMA,BCE,3,1,+,-,5.57±1.87,4.11±0.80,45.67±13.26,0.62±0.10,0.04±0.26
169,Transformer:encoder,ARIMA,MSE(logit),3,2,+,+,1.52±0.40,1.34±0.31,0.95±0.07,0.33±0.06,0.76±0.05
170,Transformer:encoder,ARIMA,BCE,3,2,+,+,1.28±0.34,1.40±0.16,4.33±3.43,0.29±0.01,0.83±0.02
171,Transformer:encoder,ARIMA,MSE(logit),3,2,+,-,6.15±1.71,3.38±0.65,6.42±4.26,0.74±0.09,0.20±0.17
172,Transformer:encoder,ARIMA,BCE,3,2,+,-,5.71±1.51,3.88±0.41,59.30±27.34,0.64±0.06,0.17±0.12
173,Transformer:encoder,ARIMA,MSE(logit),3,4,+,+,2.47±0.94,1.76±0.37,1.06±0.21,0.35±0.05,0.68±0.10
174,Transformer:encoder,ARIMA,BCE,3,4,+,+,1.18±0.35,1.31±0.20,8.88±1.92,0.31±0.02,0.83±0.02
175,Transformer:encoder,ARIMA,MSE(logit),3,4,+,-,6.67±1.12,3.66±0.45,5.23±1.56,0.67±0.08,0.17±0.14
176,Transformer:encoder,ARIMA,BCE,3,4,+,-,5.56±1.26,3.96±0.46,42.09±22.79,0.61±0.08,0.17±0.06
177,Transformer:encoder,ARIMA,MSE(logit),4,1,+,+,2.46±1.10,1.75±0.47,1.19±0.22,0.34±0.02,0.68±0.06
178,Transformer:encoder,ARIMA,BCE,4,1,+,+,1.14±0.35,1.36±0.24,5.56±2.55,0.31±0.04,0.83±0.04
179,Transformer:encoder,ARIMA,MSE(logit),4,1,+,-,4.19±1.12,2.77±0.45,3.37±0.64,0.68±0.10,0.26±0.14
180,Transformer:encoder,ARIMA,BCE,4,1,+,-,5.69±1.94,3.48±0.60,28.93±8.54,0.71±0.13,0.18±0.17
181,Transformer:encoder,ARIMA,MSE(logit),4,2,+,+,1.96±0.80,1.46±0.32,1.08±0.23,0.34±0.07,0.68±0.10
182,Transformer:encoder,ARIMA,BCE,4,2,+,+,1.34±0.50,1.33±0.23,9.42±13.70,0.28±0.03,0.82±0.04
183,Transformer:encoder,ARIMA,MSE(logit),4,2,+,-,4.32±0.67,2.70±0.21,4.91±1.34,0.67±0.08,0.30±0.07
184,Transformer:encoder,ARIMA,BCE,4,2,+,-,5.71±1.48,3.65±0.57,39.23±24.22,0.59±0.06,0.22±0.11
185,Transformer:encoder,ARIMA,MSE(logit),4,4,+,+,2.93±1.47,2.02±0.49,1.26±0.28,0.39±0.05,0.63±0.12
186,Transformer:encoder,ARIMA,BCE,4,4,+,+,1.43±0.65,1.45±0.33,7.75±4.61,0.31±0.04,0.80±0.05
187,Transformer:encoder,ARIMA,MSE(logit),4,4,+,-,5.30±0.72,2.96±0.39,7.09±4.87,0.65±0.04,0.30±0.09
188,Transformer:encoder,ARIMA,BCE,4,4,+,-,5.02±1.93,3.49±0.67,28.37±15.94,0.61±0.08,0.23±0.21
189,Transformer:encoder,ARIMA,MSE(logit),1,1,-,+,1.94±0.50,1.59±0.22,1.26±0.19,0.36±0.06,0.74±0.09
190,Transformer:encoder,ARIMA,BCE,1,1,-,+,1.15±0.28,1.28±0.19,7.44±0.99,0.32±0.02,0.82±0.02
191,Transformer:encoder,ARIMA,MSE(logit),1,1,-,-,1.01±0.75,1.26±0.34,1.35±0.10,0.31±0.04,0.85±0.09
192,Transformer:encoder,ARIMA,BCE,1,1,-,-,1.08±0.42,1.35±0.26,10.39±2.99,0.30±0.02,0.83±0.05
193,Transformer:encoder,ARIMA,MSE(logit),1,2,-,+,2.23±0.53,1.66±0.24,1.19±0.18,0.34±0.02,0.69±0.06
194,Transformer:encoder,ARIMA,BCE,1,2,-,+,1.01±0.59,1.20±0.18,9.77±2.42,0.29±0.03,0.85±0.06
195,Transformer:encoder,ARIMA,MSE(logit),1,2,-,-,1.17±0.55,1.25±0.19,1.37±0.16,0.32±0.04,0.81±0.05
196,Transformer:encoder,ARIMA,BCE,1,2,-,-,1.34±0.37,1.45±0.11,7.49±4.18,0.29±0.02,0.84±0.03